version: '3.8'
services:
  server:
    container_name: gbif-extinct
    image: hannesoberreiter/gbif-extinct:latest
    restart: always
    #entrypoint: ['bin/bash']
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    environment:
      SQL_PATH: ./db/duck.db
      USER_AGENT_PREFIX: production
    volumes:
      - ./db:/db
    ports:
      - 1323:1323
    logging:
      driver: "local"