/* Add synonym logic */
ALTER TABLE taxa ADD COLUMN isSynonym BOOLEAN DEFAULT FALSE;
ALTER TABLE taxa ADD COLUMN SynonymID BIGINT DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN SynonymName VARCHAR DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN BasionymID BIGINT DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN BasionymName VARCHAR DEFAULT NULL;