/* Add synonym logic */
ALTER TABLE taxa ADD COLUMN IF NOT EXISTS isSynonym BOOLEAN DEFAULT FALSE;
ALTER TABLE taxa ADD COLUMN IF NOT EXISTS SynonymID BIGINT DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN IF NOT EXISTS SynonymName VARCHAR DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN IF NOT EXISTS BasionymID BIGINT DEFAULT NULL;
ALTER TABLE taxa ADD COLUMN IF NOT EXISTS BasionymName VARCHAR DEFAULT NULL;